### PR TITLE
Fix for Vs2015 references

### PR DESCRIPTION
**Pull request by mika76**
These are the changes I made to make it work with Visual Studio 2015, in case you would like to merge with the code. I doubt this can be made to work with all versions so I think you're going to need to create two releases.

### CODE REVIEW

**Comment by M-Zuber** [comment]
+1

**Comment by SeriousM** [comment]
:+1:

**Comment by SeriousM** [comment]
Tested on VS2015 and it works like a charm

**Comment by stephenmcd1** [comment]
:+1: With these changes, the extension works in VS2015 for me as well.

**Comment by gentoo90** [comment]
:+1:

**Comment by SeriousM** [comment]
@nagits Could you please accept this PR? The version https://github.com/mika76/TfsPendingChangesMargin/releases/tag/1.1.1.VS2015 works like a charm for a machine without any vs installation but vs2015!
Thank you.

**Comment by M-Zuber** [comment]
:shipit: Thank you very much

**Comment by nagits** [comment]
Sorry for my lateness.
I have no opportunity to test these changes, because I don't have VS (my range of interests has changed a bit, sorry), but I believe you that it works.

Thank you for the fix!

**Comment by SeriousM** [comment]
Thank you! Is it released on vs gallery?

**Comment by nagits** [comment]
Not yet. Within two days I will make release.

**Comment by al3xnag** [comment]
cc @SeriousM 
v1.1.2 with these changes (and additionally 2e937194c5ff54fed845b4313792e95abb8cb463) released on VisualStudioGallery.

**Comment by sheitmann** [comment]
v1.1.2 doesn't work for me. I get an error during loading.
reverting back to the v1.1.1 with compatibility fix. that works for me.

**Comment by gentoo90** [comment]
Same here.
ActivityLog says:

``` xml
  <entry>
    <record>564</record>
    <time>2016/03/04 10:36:46.237</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCore..ctor(IWpfTextView textView, ITextDocumentFactoryService textDocumentFactoryService, SVsServiceProvider vsServiceProvider, IEditorFormatMapService formatMapService, IScrollMapFactoryService scrollMapFactoryService)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.&lt;&gt;c__DisplayClass0.&lt;GetMarginCore&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.GetMarginCore(IWpfTextViewHost textViewHost)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.EditorMarginFactory.CreateMargin(IWpfTextViewHost textViewHost, IWpfTextViewMargin marginContainer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>
```

**Comment by gentoo90** [comment]
1.1.2 lacks some `dll`s.
Here's the difference between patched 1.1.1 and 1.1.2
-works fails - meld

**Comment by gentoo90** [comment]
@nagits any news on this one?

**Comment by SeriousM** [comment]
> 1.1.2 lacks some dlls.
> Here's the difference between patched 1.1.1 and 1.1.2 (image...)

I get the error in the activity log

``` xml
  <entry>
    <record>677</record>
    <time>2016/03/21 12:37:04.135</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCore..ctor(IWpfTextView textView, ITextDocumentFactoryService textDocumentFactoryService, SVsServiceProvider vsServiceProvider, IEditorFormatMapService formatMapService, IScrollMapFactoryService scrollMapFactoryService)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.&lt;&gt;c__DisplayClass0.&lt;GetMarginCore&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.GetMarginCore(IWpfTextViewHost textViewHost)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.EditorMarginFactory.CreateMargin(IWpfTextViewHost textViewHost, IWpfTextViewMargin marginContainer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>
  <entry>
    <record>678</record>
    <time>2016/03/21 12:37:04.172</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.TeamFoundation.Diff, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCore..ctor(IWpfTextView textView, ITextDocumentFactoryService textDocumentFactoryService, SVsServiceProvider vsServiceProvider, IEditorFormatMapService formatMapService, IScrollMapFactoryService scrollMapFactoryService)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.&lt;&gt;c__DisplayClass0.&lt;GetMarginCore&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.MarginCoreFactory.GetMarginCore(IWpfTextViewHost textViewHost)&#x000D;&#x000A;   at AlekseyNagovitsyn.TfsPendingChangesMargin.ScrollbarMarginFactory.CreateMargin(IWpfTextViewHost textViewHost, IWpfTextViewMargin marginContainer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
  </entry>
  <entry>
```

This is definitely connected with the missing dll's.
@nagits could you please update the package to contain the dll's again please?
If you don't have them, one of us can provide them...

**Comment by sheitmann** [comment]
perhaps we need to create a new issue for this
I guess https://github.com/nagits/TfsPendingChangesMargin/issues/18 is also related to this. the references in the project do not have a version in it to make it work on 2013 and 2015 however for me it seems that doesn't work very well.
my colleague who is using vs15 and vs13 is getting errors in both.

**Pull request merged**
